Djessy-lab/Chit-Chat

- app/controllers/comment_likes_controller.rb
- app/controllers/post_likes_controller.rb
- app/views/layouts/application.html.erb
- db/seeds.rb
Methods post likes / comment likes
> Methods post likes

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/config/_variables.scss
- app/views/layouts/application.html.erb
- app/views/shared/_navbar.html.erb
front add container variable color
> front add container variable color

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/components/_navmenu.scss
- app/views/layouts/application.html.erb
- app/views/shared/_navbar.html.erb
- app/views/shared/_navmenu.html.erb
> add navbar navmenu

- app/assets/stylesheets/components/_avatar.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/components/_navmenu.scss
- app/assets/stylesheets/config/_variables.scss
- app/views/shared/_navbar.html.erb
- app/views/shared/_navmenu.html.erb
add text navmenu delete icon navbar
> add text navmenu delete icon navbar

- app/assets/stylesheets/components/_button_plus_modal.scss
- app/assets/stylesheets/components/_card_post.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/config/_variables.scss
- app/views/posts/index.html.erb
> card post border

- app/assets/stylesheets/components/_card_post.scss
- app/assets/stylesheets/config/_variables.scss
- app/views/posts/_content.html.erb
J'ai rajouté les petites têtes des enfants concernés par les posts
> content des posts finish

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_form_post.scss
- app/assets/stylesheets/components/_post_add_like_comment.scss
- app/assets/stylesheets/config/_variables.scss
- app/views/comments/_form.html.erb
- app/views/posts/_add_like_comment.html.erb
- app/views/posts/_see_like_comment.html.erb
> css com collapse

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_button_plus_modal.scss
- app/views/layouts/application.html.erb
- app/views/posts/_modal_create.html.erb
- app/views/posts/index.html.erb
> position button and contenu

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_button_plus_modal.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/custom/_devise_styles.scss
- app/views/devise/sessions/new.html.erb
- app/views/posts/index.html.erb
- app/views/shared/_navbar.html.erb
> button if ok and navbar

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_card_post.scss
- app/assets/stylesheets/components/_post_photos.scss
> contenu margin-top

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_button_plus_modal.scss
- app/assets/stylesheets/pages/_profile.scss
> update position button posts

- app/assets/stylesheets/components/_card_post.scss
- app/assets/stylesheets/custom/_devise_styles.scss
- app/assets/stylesheets/pages/_profile.scss
- app/views/devise/sessions/new.html.erb
- app/views/layouts/application.html.erb
- app/views/posts/index.html.erb
- app/views/users/show.html.erb
> update page login

- app/assets/stylesheets/config/_variables.scss
- app/assets/stylesheets/custom/_devise_styles.scss
- app/assets/stylesheets/pages/_profile.scss
> background input

- app/views/feedbacks/index.html.erb
- app/views/pages/feedbacks.html.erb
> css-feedback

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/pages/_feedback.scss
- app/views/pages/feedbacks.html.erb
> start css page feedback

- app/javascript/controllers/select_child_feed_controller.js
- yarn.lock
> if-select-backround-feed

- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/pages/_feedback.scss
- app/javascript/controllers/index.js
- app/javascript/controllers/navbar_hide_scrolldown_controller.js
- app/views/feedbacks/_diaper_form.html.erb
- app/views/feedbacks/_food_form.html.erb
- app/views/feedbacks/_sleep_form.html.erb
- app/views/shared/_navbar.html.erb
> stimilus hide navbar

- app/assets/stylesheets/components/_navbar.scss
- app/javascript/controllers/navbar_hide_scrolldown_controller.js
- app/views/shared/_navbar.html.erb
> navbar-scroll

- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/components/_navmenu.scss
- app/assets/stylesheets/pages/_chat.scss
- app/javascript/controllers/navbar_hide_scrolldown_controller.js
> navar-en-attente

- app/assets/stylesheets/components/_modal.scss
- app/javascript/controllers/navbar_hide_scrolldown_controller.js
- app/views/posts/_avatar_update_destroy.html.erb
- app/views/posts/_modal_create.html.erb
> update modal head

- app/controllers/pages_controller.rb
- app/controllers/papers_controller.rb
- app/javascript/controllers/select_child_feed_controller.js
- app/models/child.rb
- app/views/pages/papers.html.erb
- app/views/papers/_papers.html.erb
- app/views/papers/index.html.erb
- app/views/papers/new.html.erb
- app/views/papers/show.html.erb
- app/views/shared/_navmenu.html.erb
- config/routes.rb
> paper-select-child

- app/assets/stylesheets/pages/_paper.scss
> update css page new
